---
title: "Einleitung"
author: "Christoph Bader"
date: "`r Sys.Date()`"
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: "Buch Nachhaltigkeitsinitiativen"
output: bookdown::gitbook


---


# Natürliche Belastbarkeitsgrenzen unseres Planeten unter Druck  {#einleitung}


Die Art und Weise wie wir heute in der Schweiz und anderen reichen Ländern des Globalen Nordens konsumieren und produzieren bedingt einen sehr hohen Einsatz vielerlei Rohstoffe und benötigt einen hohen Energieeinsatz, welcher immer noch zum grössten Teil aus fossilen Energiequellen stammt. Zudem emittieren wir grosse Mengen verschiedenster Emissionen und hinterlassen Abfallberge, welche sich vielfach nur über sehr lange Zeiträume, wenn überhaupt, abbauen. Damit überschreiten wir mehrere ökologische Belastbarkeitsgrenzen unseres Planeten, namentlich …. (Quelle 2022). Das Global Footprint Network schätzt, dass wir im Jahr 2022 bereits Ende Juli weltweit diejenigen natürlichen Ressourcen aufgebraucht hatten, welche die Erde innerhalb eines Jahres regenerieren kann (Global Footprint Network, 2022). Dieser sogenannte «Earth Overshoot Day» veranschaulicht damit die Problematik der globalen Übernutzung der natürlichen Ressourcen und drückt aus, dass alle Rohstoffe, Materialen und Emissionen, welche wir nach dem Stichtag konsumieren, respektive emittieren, auf Kosten des Zustands unserer natürlichen Ökosysteme gehen. Das heisst, wir konsumieren jährlich mehr, als unsere Ökosysteme absorbieren und auf erneuerbare Weise zur Verfügung stellen können – kurz: wir leben damit auf einem zu grossen ökologischen Fuss. Die Problematik akzentuiert sich insbesondere an unserem Verbrauch fossiler Energie, denn die Absorbierung der Treibhausgase macht ungefähr 70% des ökologischen Fussabdrucks aus. Aber auch … haben relevante Anteile am Fussabdruck (global, Quelle). Betrachtet man nicht nur den «Earth Overshoot Day», sondern auch diejenigen verschiedener Länder, so wird deutlich, dass die Verantwortung für den Überkonsum insbesondere bei den reichen Nationen des Globalen Nordens, sowie den erdölfördernden Ländern liegt. Diese beanspruchen mit ihrem hohen Konsumniveau die natürlichen Ressourcen übermässig. So hatte beispielsweise die Schweiz das ihren Bewohnerinnen und Bewohnern zur Verfügung stehende ökologische Budget im Jahr 2022 bereits am 13. Mai ausgeschöpft, während Land X erst am XX XX und Land Y gar nicht (Quelle). Gemäss dem Globale Footprint Network bedeutet dies, dass wir fast drei Erden (ungefähr 2.8 Erden) brauchen würden, wenn alle Menschen auf der Welt so leben und konsumieren würden wie wir in der Schweiz. Zudem benötigen wir damit mehr als das Vierfache der Biokapazität, welche uns in der Schweiz zur Verfügung steht (Quelle). Wir lösen dieses Dilemma im Moment, indem wir einen grossen Teil unseres Bedarfs aus dem Ausland importieren und damit die durch unseren Konsum verursachten Umweltbelastungen in andere Länder ausgliedern (Quelle BAFU). Unser Lebensstil ist damit nicht nur global nicht verallgemeinerbar, sondern er geht auch auf Kosten ärmerer Länder. Diese weisen nicht nur tiefere Wohlstandsniveaus auf, sondern bekommen auch die Folgen der ökologischer Katastrophen überproportional zu spüren (Quelle). Wir überschreiten mit unserem hohen Konsum also nicht nur die ökologischen Belastbarkeitsgrenzen sondern akzentuieren auch globale Ungleichheiten (Quelle). 

## Eine Konsum-und Produktionswende als gesamtgesellschaftliche Aufgabe 

Die Problematik der konsumbedingten Übernutzung der natürlichen Ressourcen ist nicht neu, so wiesen bereits vor über 50 Jahren mit dem Bericht «Grenzen des Wachstums» Wissenschaftler*innen darauf hin, dass unsere wachstumsbasierte Produktions- und Konsumweise an planetare Grenzen stossen wird (Quelle). Das Ziel, nachhaltigere Konsum- und Produktionsmuster zu fördern fand seither Einzug in Globale Programme, nationale Gesetzgebungen und und lokale Strategien. So war die Förderung nachhaltiger Konsum- und Produktionsmuster bereits eine Forderung/Postulat(?) in der Deklaration des UN Gipfels in Rio 1992 (Quelle). Unter dem Motto «think global, act local» lancierten die Vereinten Nationen am an diesem Gipfel die Agenda 21 (Quelle). Ab 2002 verfolgte die Uno das 10-jahres Programm zu nachhaltigem Konsumieren und Produzieren und ab 2015 ist dem nachhaltigen Konsumieren und Produzieren in der UN Agenda 2030 ein spezifisches Ziel ( das Ziel 12) gewidmet. Dieses fordert, weltweit nachhaltige Konsum- und Produktionsmuster sicher zu stellen (Quelle). Auch die Schweiz hat sich verschiedentlich zum Schutz der planetaren Grenzen bekannt, so beispielsweise im Pariser Klimaabkommen von 2015 (Quelle) und ihrer Strategie Nachhaltige Entwicklung 2030 (Quelle), welche nachhaltige Konsum- und Produktionsmuster als eines der drei Schwerpunktthemen definiert.  

Trotz aller bisherigen Strategien, Aktionspläne und Kampagnen steigt der Verbrauch natürlicher Ressourcen global weiter an (Quelle) und eine absolute Entkopplung unseres Wirtschaftens vom Verbrauch natürlicher Ressourcen ist bisher nicht gelungen (Haberl). In der Schweiz => Fussabdrücke der Schweiz beschreiben (Trendwende, die nun beschleunigt werden muss, oder sogar Trendwende noch nicht in Sicht?). Angesichts der drohenden ökologischen Katastrophen müsste jedoch sowohl die Geschwindigkeit wie auch der Umfang der Bemühungen dringend erhöht werden (Quelle).  

Es stellt sich also die Frage, warum eine Trendwende so schwierig ist. Vielfach wird die Hauptverantwortung auf die Konsumierenden geschoben. Zahlreiche Informations- und Sensibilisierungsprogramme bis hin zu Energiesparappellen versuchen, Konsumierende zu motivieren, nachhaltigere Konsumentscheide zu fällen. Solche Ansätze ignorieren jedoch, dass nachhaltige Konsumoptionen in den meisten Fällen aktuell immer noch aufwändiger, unbequemer und teurer als die konventionelle Konsumoption sind. Sie bedingen daher ein starkes Mass an Idealismus seitens der Konsumierenden. Angesicht der Komplexität der ökologischen Probleme fühlen sich viele Menschen jedoch hilflos und tendieren dazu, den Beitrag, den sie mit ihren Entscheiden selber leisten können als nichtig zu sehen und die Verantwortung fürs Handeln bei anderen zu suchen (Lacroix et al., 2019) (ev. auch SHED oder Umweltsurvey. Daten). Um eine relevante Breitenwirkung zu erzielen, müssen also die Rahmenbedingungen von Konsumentscheiden so umgestaltet werden, dass die nachhaltigere Option zur einfachsten, naheliegendsten und attraktivsten Variante wird, die Menschen müssen überzeugt sein, dass sie auch wirklich einen wirkungsvollen Beitrag leisten können und ihr soziales Umfeld muss dies auch als wichtig und richtig erachten. (Heitfeld, 2022). 

  

Rahmenbedingungen zu gestalten, welche nachhaltiges Konsummieren und Produzieren zum neuen Normal machen, ist jedoch eine umfassende gesamtgesellschaftliche Aufgabe. Denn leider wird es nicht ausreichen, dank technologischer Fortschritte den Anteil erneuerbarer Energieproduktion etwas zu erhöhen. Es wird auch nicht ausreichen, wenn einzelne Unternehmen ihre Produktionsprozesse energie-effizienter gestalten. Und auch mit der Verschärfung einzelner Gesetze und Emissionsgrenzwerte wird sich der Wandel nicht einstellen, zumal dieser Weg zumindest in demokratisch organisierten Gesellschaften eine breite gesellschaftliche Akzeptanz bedingt, welche sich wiederum zumindest teilweise aus den Implikationen neuer Regelungen für die eigenen Konsumentscheide ergibt (Quelle). Vielmehr wird es all diese Bestrebungen, und noch einige mehr brauchen. Der benötigte  Wandel fällt so schwer, weil die Art und Weise, wie wir aktuell Konsumieren und Produzieren, zahlreiche wenn nicht fast sämtliche Lebens- Wirtschafts- und Politikbereiche unserer Gesellschaft durchdringt und prägt, und diese Bereiche eng miteinander verwoben sind. Der benötigte Wandel ist nur zu schaffen, wenn sich diese verschiedenen gesellschaftlichen, ökonomischen, politisch-institutionellen und infrastrukturell/technologischen Bereiche gemeinsam und aufeinander abgestimmt in eine nachhaltigere Richtung entwickeln. 

Forscherinnen und Forscher fordern in dem Zusammenhang von eine grosse Transformation (WGBU, Schneidewind 2018) und ein Wandel hin zu einer Postwachstumsgesellschaft (Quellen). Forderung aus dem IPBES und dem IPCC hier bringen. 

## Zivilgesellschaftliche/Gemeinwohlorientierte Nachhaltigkeitsinitiativen  als Triebkräfte von Wandel 

Beide Bereiche - Konsumentscheide und die entsprechenden Rahmenbedingungen - müssen sich also verändern, und dies zwar gemeinsam und aufeinander abgestimmt. Wissenschaftler:innen, welche sich mit näher mit solchen Nachhaltigkeitstransitionen befassen, verstehen Wandel denn auch als komplexen Prozess, in welchem sich verschiedene gesellschaftliche Subsysteme auf mehreren Ebenen gleichzeitig, und aufeinander abgestimmt verändern. Das in der Forschung zu sozio-technischen Nachhaltigkeitstransitionen häufig verwendete Mehrebenen-Modell liefert hier einen unterstützenden Denkrahmen (Geels, 2019 und eine weitere Quelle nennen). Gemäss diesem Denkrahmen entsteht gesellschaftlicher Wandel durch Experimentieren und Ausprobieren mit neuen Ideen, sogenannten Innovationen, in gesellschaftlichen Nischen. Bei Innovationen denkt man klassischerweise an neue technologische Lösungen. Aber auch neue Varianten nachhaltigerer Produkte, Dienstleistungen, Geschäfts- und Finanzierungsmodelle, Zusammenarbeitsformen sowie Konsum- und Lebensstile beginnen im Kleinen. Dies, wenn sich engagierte Personen in zivilgesellschaftlichen Nachhaltigkeitsinitiativen zusammentun um Neues auszuprobieren. So haben beispielsweise in den letzten Jahren nicht nur Repair Cafés und Unverpackt Läden, sondern auch Energiegenossenschaften, Kleidertauschbörsen, Fahrradleihsysteme und vertragslandwirtschaftliche Projekte, um nur einige Beispiele zu nennen, es zunehmend geschafft, zumindest in urbanen Regionen attraktive Alternativen zu den bisherigen Konsumoptionen zu etablieren. Das Wichtige dabei ist, das dieses Experimentieren und Ausprobieren in Nischen gesellschaftliche Lernprozesse in Gang zu setzt. Gelungene Beispiele expandieren und sie finden Nachahmer*innnen, welche die ursprüngliche Idee aufgreifen und weiterentwickeln. Nach und nach erfolgt eine gewisse Normierung, Standards und Best Practices bilden sich heraus. Dies unterstützt eine Verbreitung zusätzlich, bis die neue Idee plötzlich zu einer ernsthaften Konkurrenz der bisher vorherrschenden Konsumvariante, das heisst, zum neuen Normal wird (Augenstein et. al. 2020). Auch wenn es sich empirisch nicht beweisen lässt, so ist doch anzunehmen, dass Unverpacktläden einen Beitrag zu einem erhöhten gesellschaftlichen Bewusstsein der Plastikproblematik geleistet haben, welches wiederum nicht nur Grossverteiler zu einem Überdenken ihrer Praxis zwang, sondern auch die gesellschaftliche Akzeptanz für ein EU-weites Plastik-Verbot ebnete. Auch wäre der durch die Energiekrise ausgelöste aktuelle Boom zum Bau von Solaranlagen kaum zu bewältigen, gäbe es nicht bereits zahlreiche Energiegenossenschaften, welche verschiedene Varianten – von Selbstbau übers Anmieten von Dachflächen bis hin zur gemeinsamen Energieallmende - im Vorfeld ausgetestet und verfeinert hätten. Zivilgesellschaftliche Nachhaltigkeitsinitiativen sind damit wichtige Impulsgeber / Treibkräfte für den dringend notwendigen Wandel Richtung nachhaltigerer Zukunft (Quelle). 

  

Vielfach entstehen solche innovativen Experimente dank engagierten Personen, welche sich von den grossen gesellschaftlichen Herausforderungen nicht entmutigen lassen, sondern nach Lösungen suchen, wie unsere Konsum- und Produktionssysteme nachhaltiger gebaut/gestaltet werden könnten. So sind in den letzten Jahren zahlreiche Projekte und Initiativen entstanden, welche neue Formen des Konsumierens und Produzierens ausprobieren. Solche Initiativen können unterschiedliche Formen annehmen, sie reichen von eher losen und informellen und vielleicht auch nur temporären Gruppen von Menschen, über Vereine und Genossenschaften, bis hin zu Initiativen, welche sich als Startups aufstellen. Gemeinsam ist ihnen, dass ihre Motivation daraus resultiert, Antworten auf grössere gesellschaftliche/ umweltrelevante Probleme zu suchen, und nicht profit-orientierten Geschäftsinteressen im Mittelpunkt stehen (Grabs et al. 2026, Geels, 2019, Hossain 2018). Der Charakter des Experimentierens mit neuen Ideen bringt es aber mit sich das gute Ideen auf dem Weg aus der Nische in die Gesellschaft auf zahlreiche Herausforderungen und Hindernisse stossen. (ev. ein paar Beispiele nennen?). Zwar entstanden und entstehen in den letzten Jahren zahlreiche Initiativen, viele von ihnen verschwinden nach eher kurzer Zeit wieder von der Bildfläche. (ev. mal Liste aus ZH Bericht überprüfen). Insbesondere die Etablierung und das längerfristige Überleben stellt für viele Initiativen eine Knacknuss dar (ev. ZH Bericht hier zitieren). Ein besseres Verständnis darüber, wie diese umschifft oder gemeistert werden können, kann den benötigten Experimentier- und Lernprozess unterstützen und damit das Potential von Impulsen für Wandel in Wert setzen (Quelle). 

::: {.defbox data-latex=""}
Kasten: 
Zivilgesellschaftliche Nachhaltigkeitsinitiativen -einige Beispiele (nicht unbedingt die Beispiele, die wir dann weiter hinten im Detail bringen) 

Beispiele z.B. aufgrund der Tabelle in der Intro in Zh-Bericht 
- Repair cafe 
- Vertragslandwirtschaft 
- Unverpackt Läden 
- Leihfahrräder 
- Tauschbörsen 
- Re- upcycle 
Etc.
:::



