---
title: "Wege der Verbreitung von Nachhaltigkeitsinitiativen"
author: "Christoph Bader"
date: "`r Sys.Date()`"
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: "Buch Nachhaltigkeitsinitiativen"
output: bookdown::gitbook
---

# Theoretischer Hintergrund - wissenschaftliche Debatte {#Teil1}

Die aktuellen Herausforderungen des 21. Jahrhunderts wie bspw. der Klimawandel, soziale Ungleichheiten, Verlust der Biodiversität oder die Übernutzung (natürlicher) Ressourcen sowie die damit verbundenen gesamtgesellschaftlichen Probleme bündeln sich in der Debatte um eine nachhaltige Entwicklung. Weitestgehend Konsens besteht darin, dass der nötige Umbau der Gesellschaft unter dem Leitbild nachhaltiger Entwicklung nur unter Beteiligung aller gesellschaftlichen Akteure zu bewerkstelligen ist (WBGU, 2011; GSDR, 2019). 

Seit nun mehr als 30 Jahren werden Ansätze erprobt, welche unterschiedliche Zielgruppen dazu motivieren soll, nachhaltiger zu produzieren und konsumieren. Dabei sind Versuche vorherrschend, welche mittels Anreize oder technologischen Lösungen versuchen, unsere Produktions- und Konsummuster zu beeinflussen bzw. nachhaltiger zu gestalten. Komplementiert werden diese Ansätze mit Sensibilisierungskampagnen und Wissensvermittlung über nachhaltige Konsum- und Produktionsformen. Nicht zuletzt aufgrund empirischer Studien zu den Rebound-Effekten (Parrique et al., 2019), mehren sich die Anzeichen, dass alleine mit technologischen Fortschritten der benötigte Wandel hin zu einer nachhaltigen Gesellschaft wohl nicht innerhalb der benötigten Zeit zu schaffen ist. Berichte wie der IPCC Working Group Report Nr. 6 (IPCC, 2022) oder die Studie vom europäischen Umweltbüro (EEB, 2019) zeigen auf, dass trotz Teilerfolgen insgesamt keine Trendwende in Sicht ist. Einige Länder erreichen eine relative Entkopplung, indem ihre Volkswirtschaften stärker wachsen als der Ressourcenverbrauch, was wir jedoch angesichts der wissenschaftlichen Erkenntnisse bräuchten, ist eine absolute Entkopplung von Wirtschaftswachstum und Ressourcenverbrauch. Dies bedeutet, dass der Ressourcenverbrauch und damit die Treibhausgasemissionen absolut reduziert werden müssen und nicht lediglich im Verhältnis zum Wirtschaftswachstum kleiner ausfallen. 

In vielen nachhaltigkeitsrelevanten Bereichen, wie der alltäglichen Ernährung, Mobilität oder Energienutzung, sind konsumentenbezogene Strategien trotz langjähriger Interventionsforschung und -praxis auch weiterhin mit komplexen Herausforderungen konfrontiert. Konsumbezogene Entscheidungen und Handlungen sind ein Teil sozialer Praktiken, die, in individuelle Alltagsabläufe und infrastrukturelle Rahmenbedingungen eingebettet, relativ erfolgreich funktionieren und deshalb nur schwer veränderbar sind (Jaeger-Erben/Schäfer 2010, Spaargaren/van Vliet 2000, John 2013). Deshalb ist ein struktureller Wandel des Konsums- und Produktionssystem unerlässlich für die Erreichung der Nachhaltigkeitsziele. 

Vor diesem Problemhintergrund werden seit einiger Zeit verschiedene neue Konsum- und Produktionsformen wie das Teilen von Gegenständen, vertragslandwirtschaftliche Projekte, Reparierangebote, Upcycling, Prosuming sowie neue Organsationsformen (u.a. Soziokratie und Holokratie), welche die Konsumgewohnheiten sowie die Produktion hin zu mehr Nachhaltigkeit verändern können. Solche zivilgesellschaftlichen Initiativen werden auch als soziale Innovationen bezeichnet (Rückert-John, 2013). Sie können einerseits suffizientere Lebensstile fördern, indem sie den Menschen ressourcenleichtere Handlungsalternativen bereitstellen und Verhaltensänderungen erleichtern. Andererseits können von ihnen Impulse ausgehen zur Umgestaltung der aktuell vorherrschenden ressourcenintensiven Wirtschaftsweise. Dies vor allem, wenn eine Etablierung und Institutionalisierung der Initiativen gelingt, wenn ihre Idee in anderen Regionen und Handlungsfeldern aufgegriffen, repliziert und weiterentwickelt wird und nicht zuletzt, wenn eine starke gemeinsame Interessenvertretung entsteht, welche sich für eine Anpassung infrastruktureller, regulativer und ökonomischer Strukturen an die Bedürfnisse der Initiativen und ihrer Nutzenden einsetzt (Moser et al, 2018). So werden von der politischen Seite grosse Hoffnungen mit sozialen Innovationen verbunden (quellen), da sie «aus der Gesellschaft heraus» neue Lösungen für gegenwärtige Probleme kreieren und sich dadurch besser verbreiten und eine stärkere Akzeptanz finden (Rückert-John et al. 2013, Beck/Kropp 2011, Howaldt/Schwarz 2010, Howaldt/Jacobsen 2010). 

Jedoch ist die Förderung und Unterstützung solcher sozialen Innovationen in der Nachhaltigkeits- und Transformationsdebatte noch kaum ein etabliertes Instrument für eine zielgerichtete Nachhaltigkeitspolitik im Sinne der Umsetzung der Agenda 2030. Einerseits sind die Phänomene, die als soziale Innovation bezeichnet werden sehr vielfältig, so dass die Definitionen häufig sehr allgemein bleiben und damit oft unbrauchbar für eine Entfaltung von gesellschaftspolitischer Relevanz. Andererseits fehlen Erkenntnisse darüber, welche Faktoren den Bestand von sozialen Innovationen über die Gründungsphase hinaus sichern können. Dies weil sowohl die Forschung wie auch das öffentliche Interesse sich bisher vor allem Fragen der Entstehung von Nachhaltigkeitsinitiativen widmeten. Wie sich Initiativen aus der Nische heraus in der Gesellschaft etablieren, Wirkung entwickeln und damit zu einem Wandel beitragen, ist bisher hingegen kaum bekannt.  

Das vorliegende Buch hat zum Ziel, Transformationswissen, sowie gute Beispiele des Gelingens der Etablierung, Verbreitung und Verdichtung von Nachhaltigkeitsinitiativen bereitzustellen. Die übergeordnete Fragestellung lautet demnach: 

Welche Faktoren und Prozesse fördern/hemmen den erfolgreichen Übergang von der Entstehung zur Etablierung und langfristigen Bestand von Nachhaltigkeitsinitiativen, sowie der Entfaltung des gesellschaftlichen Veränderungspotentials ihrer sozialen Innovation? 

Dazu haben wir vier zentrale Herausforderungen für den langfristigen Bestand von Initiativen einerseits theoretisch abgeleitet sowie andererseits induktiv hergeleitet. Im Hauptteil des Buches portraitieren wir Projekte, welche für eine oder mehrere der vier zentralen Herausforderungen innovative Lösungen gefunden haben. 

## Nachhaltigkeitsdefinition {#beschleunigung}

Grundsätzlich orientiert sich der hier genutzte Nachhaltigkeitsbegriff an der im Brundtland Bericht verankerten Definition von 1987: „Dauerhafte (nachhaltige) Entwicklung ist Entwicklung, die die Bedürfnisse der Gegenwart befriedigt, ohne zu riskieren, dass künftige Generationen ihre eigenen Bedürfnisse nicht befriedigen können.“. Damit Nachhaltigkeit nicht lediglich regional oder national begriffen wird, verwenden wir zusätzlich das Konzept der planetaren Grenzen (Rockström et al, 2009; neuste Publikation), ergänzt mit den sozialen Zielen einer Nachhaltigen Entwicklung (Raworth, 2017). Dies ist für die Schweiz besonders zentral, da sich negative Umwelteffekte sowie soziale Folgen unserer ressourcenintensiven Konsummuster häufig in Ländern des globalen Südens manifestieren und seltener in der Schweiz.  

In Bezug auf die wissenschaftliche Debatte zu starker und schwacher Nachhaltigkeit, wird in diesem Buch von der Notwendigkeit einer starken Nachhaltigkeit ausgegangen. Demnach sind die drei Dimensionen der Ökonomie, Gesellschaft und Umwelt nicht gleichrangig zu verstehen. Vielmehr bildet die Umwelt die Grundvoraussetzung für unsere Gesellschaft und diese wiederum ist Voraussetzung für die Wirtschaft. Um die gesetzten Nachhaltigkeitsziele zu erreichen, unterscheidet die Literatur häufig drei unterschiedliche Strategien, welche sich gegenseitig bedingen: 

Effizienz richtet sich auf die ergiebigere Nutzung von Materie und Energie, also auf Ressourcenproduktivität. 

Suffizienz richtet sich auf einen geringeren Verbrauch von Ressourcen durch eine Verringerung der Nachfrage nach Gütern. 

Konsistenz richtet sich auf naturverträgliche Technologien, die die Stoffe und die Leistungen der Ökosysteme nutzen, ohne sie zu zerstören. 

Vor dem Hintergrund des vorangegangen Problembeschriebs und insbesondere der Erkenntnis, dass wir alleine mit technischen Lösungen (Effizienz- und Konsistenzstrategie) die Nachhaltigkeitsziele nicht erreichen können, fokussiert dieses Buch auf die Suffizienzstrategie. Suffizienz zielt auf Schritte, Massnahmen und Instrumente ab, mit denen natürliche Ressourcen eingespart werden können, und zwar dadurch, dass Menschen ihr Verhalten verändern mit der Absicht, Ressourcen und damit Produkte und Dienstleistungen anders zu nutzen und von ihnen weniger zu verbrauchen als bisher bei gleichbleibendem oder erhöhtem Wohlergehen. 

## Gegenstand: Nachhaltigkeitsinitiativen {#symptome_ursachen}

Zunächst stellt sich die Frage nach der konkreten Benennung bzw. Eingrenzung des Untersuchungsgegenstands. Die wissenschaftliche und öffentliche Diskussion zu den von uns untersuchten Initiativen wird aktuell unter verschiedenen Schlagwörtern geführt, beispielsweise Soziale Innovationen, Graswurzelbewegungen, zivilgesellschaftliche Initiativen, Experimente oder Reallabore. 

In diesem Buch wollen wir die vier zentralen Herausforderungen bei der Verbreitung und Etablierung von Projekten darstellen und gute Beispiele des Gelingens portraitieren, welche von zivilgesellschaftlichen Gruppen getragene Projekte, die durch ihre suffizienz-orientierten Praktiken und Prozessen positive Nachhaltigkeitseffekte erzielen und/oder ein hohes Potential aufweisen, um unsere aktuellen Produktions- und Konsummuster zu transformieren. Diese Art des nachhaltigen Handelns umschreiben wir mit dem Begriff Nachhaltigkeitsinitiativen1. Beispiele für Nachhaltigkeitsinitiativen sind Vertragslandwirtschaften, Energiegenossenschaften, Zerowaste / Unverpacktläden, Sharing-Initiativen, Reparaturwerkstätten, CoWorking und Maker Spaces sowie Initiativen welche neue Organisations- und Finanzierungsformen austesten (Penha-Lopes & Henfrey, 2019).  

Wie einleitend beschrieben, herrscht in der Debatte um Nachhaltige Entwicklung Konsens, dass wir die Nachhaltigkeitsziele nicht alleine durch technische Innovationen (effiziente und konsistente Lösungen) erreichen werden, sondern auch soziale Innovationen (suffiziente Lösungen) benötigen. Soziale Innovationen bieten Lösungen für soziale Probleme, zielen auf eine Verbesserung der Lebensqualität ab (Moulaert et al, 2013, Mulgan et al. 2007. Pol and Ville, 2009), verändern soziale Praktiken und Beziehungen und geben Ideen für neue soziale Beziehungen und Organisation (Franz et al. 2012, Mumford 2022). Die untersuchten Nachhaltigkeitsinitiativen in diesem Buch folgen dem Verständnis von sozialen Innovationen als neue Formen der Zusammenarbeit auf individueller oder organisationaler Ebene, die zu neuen Ideen führt, deren Umsetzung zumindest angedacht ist. Solche Nachhaltigkeitsinitiativen können sich positiv auf die Gesellschaft auswirken, die Lebensqualität verbessern und/oder soziale Beziehungen bzw. Machtbeziehungen verändern (angelehnt an Tschumi et al. 2020). 

Damit unterscheiden sich die untersuchten Nachhaltigkeitsinitiativen als soziale Innovationen von klassischen Innovationen (oft technischer Art) in nachstehenden Punkten: 

# Wirkung entwickeln - Wie Nachhaltigkeitsinitiativen zu gesellschaftlichen Transformationen beitragen

Wir erachten Nachhaltigkeitsinitiativen als zentralen Bestandteil des gesellschaftlichen Transformationsprozesses, da sie wichtige Impulse für alternative Lebensstile, Alltagspraktiken und Konsummuster setzen. Dabei leisten Nachhaltigkeitsinitiativen Beiträge auf unterschiedlichen Ebenen. 

Auf individueller Ebene bieten Nachhaltigkeitsinitiativen ihren Mitgliedern und Kund*innen neue, ressourcenleichtere Handlungsalternativen und tragen so zu individuellen Verhaltensänderungen bei. Wirkung auf individueller Ebene erzielen Nachhaltigkeitsinitiativen dann, wenn die neue Alternative ein ursprüngliches, weniger suffizientes Verhalten ersetzt. Das geschieht beispielsweise, wenn dank vertragslandwirtschaftlichen Angeboten vermehrt saisonale, regionale und biologisch hergestellte Nahrungsmittel konsumiert werden oder wenn fossile durch erneuerbare Energie ersetzt wird. Nachhaltigkeitsinitiativen ermöglichen und erleichterten jedoch nicht nur Gelegenheiten für Handlungsalternativen, sie können auch Wertediskussionen anregen, Gemeinschaftsgefühle fördern und neue Kompetenzen und Fähigkeiten vermitteln. Weiter können Nachhaltigkeitsinitiativen auch auf einer gesellschaftlichen Ebene wirken, beispielsweise wenn sie es schaffen, sich zu verbreiten und somit möglichst viele Leute zu erreichen und entsprechende individuelle Verhaltensänderungen anstossen sowie den aktuellen nicht-nachhaltigen Modus Operandi zu verändern. Erst dann wird sich auch eine gesamtgesellschaftliche Reduktion der verbrauchten Menge an Materialien und Energie einstellen. Eine Verbreitung muss jedoch nicht nur durch ein Wachstum einzelner Angebote entstehen, vielmehr ist das Entstehen gleicher oder ähnlicher Initiativen an neuen Standorten oder die Weiterentwicklung und Kombination bestehender Ideen im Rahmen neuer Initiativen und Angebote begrüssenswert. Gesellschaftliche Effekte können zudem erzielt werden, wenn die Verbreitung Veränderungen in gesellschaftlichen Subsystemen in Gang ruft. Beispiele für solche gesellschaftlichen indirekten Effekte sind Veränderungen bei der Infrastruktur aufgrund veränderter Nutzungsbedürfnisse, die Schaffung neuer ökonomischer Anreize oder die Anpassung rechtlicher und administrativer Rahmenbedingungen. 

# Wege der Verbreitung von Nachhaltigkeitsinitiativen 

Die Transformationsforschung geht davon aus, dass über Initiativen im Kleinen, Experimentierräumen, Pilotprojekte, Prototyping und andere Formen des Austesten, Visionen und mögliche Transformationspfade hin zu einer nachhaltigeren Gesellschaft greifbar, das Neue erfahrbar und die Vorteile sichtbar werden (u.a. Kristof, 2020; weitere). Innerhalb der Transformationsforschung gibt es unterschiedliche Perspektive auf die Frage wie Transformationen verlaufen. 

Aus dem breiten Feld der Transformationsforschung liefern für das vorliegende Buch insbesondere die beiden Ansätze der Mehrebenenperspektive soziotechnischer Transitionen (Geels, 2002; Geels & Schot, 2007; Smith et al., 2010), und des strategischen Nischenmanagements (Kemp et al., 1998; Raven and Geels, 2010; Smith, 2007) hilfreiche Konzepte. Beide Ansätze verstehen technische und soziale Innovationen und Initiativen als Aktivitäten in gesellschaftlichen Nischen und verfolgen die Frage, wie solche Nischenaktivitäten genügend Schwung und Gewicht entwickeln, um in verschiedenen gesellschaftlichen (Sub)systemen Veränderungen (d.h. Systemtransformationen) zu bewirken. Beide Ansätze haben in Bezug auf die Frage, wie im Rahmen nachhaltiger Entwicklung Transformationsprozesse angestossen werden können, eine grosse Popularität erfahren und wurden beispielsweise in Publikationen des Deutschen Umweltbundesamts (Griesshammer & Brohmann, 2015) und der Europäischen Energie Agentur (European Environment Agency, 2018) aufgegriffen. 

Die Mehreebeneperspektive analysiert sozio-technische Systeme, welche verschiedene gesellschaftliche Subsysteme, wie jene der Technologie, Infrastrukturen und Konsumgewohnheiten aber auch kulturelle Bedeutungszuschreibungen, umfassen (Geels 2010). Gemäss dieser Perspektive werden Veränderungen von Systemen durch die Wechselwirkungen von drei funktionalen Ebenen beeinflusst: dem Umfeld (englisch: „landscape“), in welcher systemexterne Herausforderungen, wie beispielsweise die Übernutzung natürlicher Ressourcen als Triebkräfte für Wandel konzeptualisiert werden. Aber auch Ereignisse wie zum Beispiel das Atomreaktorunglück in Fukushima, gesellschaftlicher Wertewandel, die Finanzkrise 2008 oder die Covid-Pandemie können als Ereignisse auf dieser übergeordneten Ebene verstanden werden, welche in diesem Fall zu Systemerschütterungen führen und somit Gelegenheitsfenster für Veränderung öffnen (Driel & Schot 2005; Smith, Voss & Grin, 2010). Die „Regime-Ebene“ wird als Ort der formellen und informellen Institutionen u.a. bestehende Technologien, Infrastrukturen, Regulationen, Anreizstrukturen, Märkte und Konsumpräferenzen, aber auch bestehender politischer und Wissenschaftssysteme als auch etablierter sozialer Praktiken verstanden, die das sozio-technische System stabilisieren und reproduzieren. Die Regime-Ebene stellt somit die Hürden für den Wandel dar. Die der Regimeebene untergeordnete Nischenebene ist der Ort, an welchem zivilgesellschaftliche Akteure, Neuerungen erproben, auch gegen bestehende institutionelle und organisationale Regeln des bestehenden Regimes. Damit werden Nischen-Akteure zu zentralen Motoren für Veränderungsprozesse und stellen Alternativen für Wandel zur Verfügung. Aus der Mehrebenenperspektive können Rückschlüsse zu Dynamiken, Mustern und Mechanismen gezogen werden, die einem Wandel zugrunde liegen, insbesondere in Hinblick auf die Rolle von in der Nische agierenden Nachhaltigkeitsinitiativen. 

Das darauf aufbauende Strategische Nischenmanagement (SNM) beschreibt, was Marktnischen sind, wie sie entstehen, wie sie sich identifizieren lassen und wie sie sich verbreiten (Schot und Geels 2008) (Kemp, Schot, und Hoogma 1998b). Angewandt auf gemeinschaftsbasierte Nachhaltigkeitsinitiativen wie beispielsweise die Transition-Towns Bewegung oder Regionalwährungen in England, haben Seyfang und Haxeltine (2012) zentrale Punkte für eine erfolgreiche Diffusion von Nischeninnovationen in sozio-technische Regime beschrieben. 

# Nischen als geschützte Räume zum Experimentieren für Nachhaltigkeitsinitiativen 

Nischen nehmen in Transformationsprozessen einen zentralen Platz ein. Es handelt sich bei dieser untersten Ebene um Räume und Situationen, in denen Neues in einer gewissen Unabhängigkeit vom bestehenden Regime entstehen kann, auch wenn die Entstehung von Nischen auch vom bestehenden Regime beeinflusst wird (Smith & Raven, 2012). Während die Strukturen auf der Ebene von Landschaft und Regime relativ stark verfestigt sind, bieten Nischen grössere Flexibilität und damit Potenzial für Veränderungen. Somit können hier radikale (soziale oder technische) Innovationen entstehen, die nicht nur eine Weiterentwicklung bestehender Strukturen darstellen und die zu einer Veränderung des Regimes führen können. Auch innerhalb des Regimes entstehen Innovationen, doch haben diese typischerweise nicht das Potenzial, zu einer Regimeveränderung zu führen.  

-> hier eventuell Beispiel 

-> wollen wir hier shielding, nurtering und empowering einführen? 

Nischen können „zufällig“ beispielsweise durch lokale Probleme innerhalb des Regimes entstehen, für die die Nischeninnovationen Lösung bereitstellen. Nischen können aber auch bewusst entwickelt werden. In einer Nische können sich Innovationen entwickeln, ohne von Beginn an dem Selektionsdruck des Regimes ausgesetzt zu sein, so wie es typischerweise bei Innovationen der Fall ist, die sich im normalen Marktumfeld behaupten und sich deshalb auch von Beginn an den bestehenden Regimestrukturen orientieren müssen. 

Bei Nischen handelt es sich nicht um einzelne Projekte oder Experimente, auch wenn in der Literatur zur Mehrebenenperspektive teilweise dieses Verständnis von Nischen besteht (Berkhout, 2011; Geels & Raven, 2006). Während Projekte und Experimente lokal und zeitlich begrenzt sind, stellen Nischen bereits eine Aggregationsebene dar, unter der verschiedene Projekte, Initiativen und Akteure vereint sind. Diese bilden in gewisser Weise bereits ein eigenes Regime, das sich aber von dem eigentlichen Regime in der Größe und vor allem auch in der Verfestigung der Strukturen unterscheidet. Eine Herausforderung für die Entwicklung von Nischen ist also die Verknüpfung von lokalen Aktivitäten (Raven et al., 2007).  

-> hier eventuell Beispiel 

## Phasen, welche über mehrere Jahrzehnte gehen 

In der Literatur der Transformationsforschung (quellen) wird ein erfolgreicher oder "idealer" Wandel hin zu einer nachhaltigen Entwicklung als die Form einer S-Kurve in drei Phasen betrachtet: von der Entstehung über die Beschleunigung bis zur Stabilisierung. In der Entstehungsphase nehmen neue innovative Ideen langsam Gestalt an und führen zu neuen Technologien und/oder neuen Praktiken. Diese Innovationen finden in Nischen und am Rande statt, oft durch Experimentieren und Lernen. Aufkommende Ideen, Technologien und Praktiken stossen auf viele Hindernisse, können aber mit der Zeit einen Wendepunkt erreichen und auf breiter Basis angenommen werden. Dies wird als Beschleunigungsphase bezeichnet. Wenn die neuen Technologien und Praktiken zur neuen Normalität werden und in unsere neue Lebensweise eingebettet sind, haben wir die Stabilisierungsphase erreicht. Dem raschen Anstieg innovativer Technologien und Praktiken steht der Rückgang nicht nachhaltiger/alter Technologien, Institutionen und Praktiken gegenüber, so dass sich eine umgekehrte S-Kurve mit drei entsprechenden Phasen ergibt: Destabilisierung (entgegen dem Aufkommen), Zusammenbruch (entgegen der Beschleunigung) und Auslaufen (entgegen der Stabilisierung).  

-> Grafik Phasen 

Interventionen zur Ermöglichung von Transformationen können auf beide Kurven abzielen - die Entstehung und Beschleunigung von Nachhaltigkeitsinitiativen bewusst unterstützen und gleichzeitig nicht nachhaltige Konfigurationen destabilisieren und auslaufen lassen. In diesem Buch fokussieren wir auf die Frage wie die Entstehung von Nachhaltigkeitsinitiativen beschleunigt werden kann und das Bestehen dieser unterstützt werden kann. 

## Die Phasen der untersuchten Nachhaltigkeitsinitiativen 


