---
title: "Herausforderungen des Entstehens und Bestehens von Nachhaltigkeitsinitiativen"
author: "Christoph Bader"
date: "`r Sys.Date()`"
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: "Buch Nachhaltigkeitsinitiativen"
output: bookdown::gitbook

---
# Herausforderungen des Entstehens und Bestehens von Nachhaltigkeitsinitiativen 

Während es eine lange Tradition gibt, zu untersuchen, wie marktbasierte Innovationen gedeihen und auf den Mainstream-Märkten Fuss fassen können, sind die zugrunde liegenden Prozesse, wie zivilgesellschaftliche Initiativen entstehen und zu Nachhaltigkeitsübergängen beitragen, weniger gut verstanden (Seyfang und Smith, 2007; Seyfang und Longhurst, 2016). Es ist bekannt, dass es allgemeine Herausforderungen im Zusammenhang mit (1) dem Aufbau und der Aufrechterhaltung einer Nachhaltigkeitsinitiative und (2) der Verbreitung von Nachhaltigkeitsinitiativen im "Mainstream" gibt (Seyfang und Smith, 2007). In der Literatur werden weitere spezifische Herausforderungen genannt, wie bspw. die Abhängigkeit von der freiwilligen Verpflichtung engagierter Mitglieder macht Nachhaltigkeitsinitiativen anfällig für das Ausscheiden von Schlüsselpersonen und eine hohe Fluktuation von Freiwilligen (Schot & Geels, 2008), die Schwierigkeit zum gemeinsamen Lernen aufgrund der fehlenden Dokumentation von Wissen und der Artikulation von “Best-Practice” Lektionen (Hossain, 2018), erschwerter Zugang zu finanziellen Ressourcen aufgrund Bekenntnis zu radikalen Werten oder gewählter Unternehmensform (Hussain, 2018) oder rechtliche oder regulatorische Unklarheiten (White & Sterling, 2013). 

Basierend auf dieser Literaturrecherche haben wir vier zentrale Herausforderungen für das Entstehen und Bestehen von Nachhaltigkeitsinitiativen in der Schweiz zusammengestellt und diese mit unterschiedlichen Stakeholdern bestehend aus Initiant:innen sowie Vertreter:innen aus der Verwaltung und Förderinstitutionen validiert und ergänzt. 

## Vier zentrale Herausforderungen für Nachhhaltigkeitsinitiativen 

*Mittel beschaffen:* Für den Erfolg von Initiativen ist es zentral, den richtigen Mix aus Spenden, Mitgliedsbeiträgen, Freiwilligenarbeit und Leistungsentgelten zu finden. Als grundlegende Herausforderung stellt sich hier, dass aktuell nur wenige Finanzierungsmöglichkeiten vorhanden sind und diese vorwiegend auf zeitlich befristete Projekte als auf eine kontinuierliche Grundleistung ausgelegt sind. Durch die Unübersichtlichkeit und Dezentralität der Finanzierungsquellen sowie grosser Konkurrenz bei deren Nachfrage ergeben sich hohe Aufwände bei der Mittelbeschaffung. 

*Rechtform:* Die Entscheidung für eine bestimmte Rechtsform zieht verschiedenste Implikationen nach sich, z.B. in Bezug auf Finanzierungsmöglichkeiten, Mitbestimmung, Verantwortlichkeiten, Haftung und Zweckorientierung.. Die Wahl einer geeigneten Rechtsform ist für Initiativen demnach entscheidend. Als grundlegende Herausforderung stellt sich hier, dass die aktuell in der Schweiz existierenden Rechtsformen entweder auf wirtschaftliche oder nicht-wirtschaftliche Zwecke ausgerichtet sind und damit den beidseitigen Bedürfnissen vieler Nachhaltigkeitsinitiativen nicht gerecht werden. Initiativen versuchen mit verschiedenen Rechtskonstrukten, der Kombination von Rechtsformen oder der Wahl neuer Rechtsformen hier einen Brückenschlag. Gleichzeitig betreten sie so Neuland, was zu Mehraufwand und juristischen Unsicherheiten führen kann. 

*Gouvernanz:* Eine gut organisierte, und auf die Ziele der Initiative angepasste interne Gouvernanz, d.h. eine explizite Struktur von Regeln, Praktiken und Prozessen, ist ein zentraler Erfolgsfaktor für das langfristige Bestehen und Agieren einer Initiative. Forschungen über den Zusammenhang zwischen der Governance von SI – Initiativen und deren Erfolg heben die Bedeutung von Strukturen hervor, die Lern- und Experimentierprozesse unterstützen. Als hierfür zentral werden erstens starke demokratische Prinzipien inklusive partizipativer Entscheidungsfindungen erachtet. Zweitens kann die Governance-Form der Initiative zu sozialen Lernprozessen beitragen, indem sie die Verbundenheit der Beteiligten fördert, genügend Raum und Opportunitäten für Entscheidungsfreiheiten der Mitglieder bietet im Rahmen ihrer eigenen Wertvorstellungen zu handeln, sowie unterstützend wirkt bei der Wahrnehmung individueller und kollektiver Selbstwirksamkeitserfahrungen. 

*Netzwerke und Interessen:* Einzelne Initiativen sind vergleichbar klein mit relativ geringem Potential zur Einflussnahme auf Rahmenbedingungen. Somit spielen Netzwerke, Dachorganisationen weitere unterstützende Akteure eine zentrale Rolle bei der Vermittlung von Wissen, Kompetenzen, Ressourcen und Erfahrungen, wie auch bei der aktiven (politischen) Einflussnahme auf die Rahmenbedingungen, welche ihrerseits das Entstehen und Bestehen von Initiativen vereinfachen/erschweren. Hierbei stellen sich nebenstehende Herausforderungen. 


:::